import { Store, SKU, Week, Month, PlanningData } from '../models/types';

// Sample data structure
export interface SampleData {
  stores: Store[];
  skus: SKU[];
  weeks: Week[];
  months: Month[];
  planningData: PlanningData[];
}

// Generate sample data
export const generateSampleData = (): SampleData => {
  // Create stores
  const stores: Store[] = [
    { id: 'ST035', label: 'San Francisco Bay Trends', city: 'San Francisco', state: 'CA' },
    { id: 'ST046', label: 'Phoenix Sunwear', city: 'Phoenix', state: 'AZ' },
    { id: 'ST064', label: 'Dallas Ranch Supply', city: 'Dallas', state: 'TX' },
    { id: 'ST066', label: 'Atlanta Outfitters', city: 'Atlanta', state: 'GA' },
    { id: 'ST073', label: 'Nashville Melody Music Store', city: 'Nashville', state: 'TN' },
    { id: 'ST074', label: 'New York Empire Eats', city: 'New York', state: 'NY' },
    { id: 'ST091', label: 'Denver Peaks Outdoor', city: 'Denver', state: 'CO' },
    { id: 'ST094', label: 'Philadelphia Liberty Market', city: 'Philadelphia', state: 'PA' },
    { id: 'ST097', label: 'Boston Harbor Books', city: 'Boston', state: 'MA' },
    { id: 'ST101', label: 'Austin Vibe Co.', city: 'Austin', state: 'TX' },
    { id: 'ST131', label: 'Los Angeles Luxe', city: 'Los Angeles', state: 'CA' },
    { id: 'ST150', label: 'Houston Harvest Market', city: 'Houston', state: 'TX' },
    { id: 'ST151', label: 'Portland Evergreen Goods', city: 'Portland', state: 'OR' },
    { id: 'ST156', label: 'Chicago Charm Boutique', city: 'Chicago', state: 'IL' },
    { id: 'ST163', label: 'Las Vegas Neon Treasures', city: 'Las Vegas', state: 'NV' },
    { id: 'ST175', label: 'Seattle Skyline Goods', city: 'Seattle', state: 'WA' },
    { id: 'ST176', label: 'Miami Breeze Apparel', city: 'Miami', state: 'FL' },
    { id: 'ST177', label: 'San Diego Wave Surf Shop', city: 'San Diego', state: 'CA' },
    { id: 'ST193', label: 'Charlotte Queen’s Closet', city: 'Charlotte', state: 'NC' },
    { id: 'ST208', label: 'Detroit Motor Gear', city: 'Detroit', state: 'MI' },
  ];

  // Create SKUs
  const skus: SKU[] = [
    {
      id: 'SK00158',
      name: 'Crew Neck Merino Wool Sweater',
      class: 'Tops',
      department: "Men's Apparel",
      price: 114.99,
      cost: 18.28,
    },
    {
      id: 'SK00269',
      name: 'Faux Leather Leggings',
      class: 'Jewelry',
      department: 'Footwear',
      price: 9.99,
      cost: 8.45,
    },
    {
      id: 'SK00300',
      name: 'Fleece-Lined Parka',
      class: 'Jewelry',
      department: 'Unisex Accessories',
      price: 199.99,
      cost: 17.8,
    },
    {
      id: 'SK00304',
      name: 'Cotton Polo Shirt',
      class: 'Tops',
      department: "Women's Apparel",
      price: 139.99,
      cost: 10.78,
    },
    {
      id: 'SK00766',
      name: 'Foldable Travel Hat',
      class: 'Tops',
      department: 'Footwear',
      price: 44.99,
      cost: 27.08,
    },
    {
      id: 'SK00786',
      name: 'Chic Quilted Wallet',
      class: 'Bottoms',
      department: 'Footwear',
      price: 14.99,
      cost: 4.02,
    },
    {
      id: 'SK00960',
      name: 'High-Slit Maxi Dress',
      class: 'Outerwear',
      department: 'Sportswear',
      price: 74.99,
      cost: 47.47,
    },
    {
      id: 'SK01183',
      name: 'Turtleneck Cable Knit Sweater',
      class: 'Footwear',
      department: 'Footwear',
      price: 49.99,
      cost: 22.6,
    },
    {
      id: 'SK01189',
      name: 'Retro-Inspired Sunglasses',
      class: 'Bottoms',
      department: "Women's Apparel",
      price: 194.99,
      cost: 115.63,
    },
    {
      id: 'SK01193',
      name: 'Stretch Denim Overalls',
      class: 'Bottoms',
      department: 'Unisex Accessories',
      price: 129.99,
      cost: 47.06,
    },
    {
      id: 'SK01249',
      name: 'Adjustable Elastic Headband',
      class: 'Footwear',
      department: "Women's Apparel",
      price: 19.99,
      cost: 1.34,
    },
    {
      id: 'SK01319',
      name: 'Adjustable Baseball Cap',
      class: 'Jewelry',
      department: "Men's Apparel",
      price: 4.99,
      cost: 2.29,
    },
    {
      id: 'SK01349',
      name: 'Cotton Polo Shirt',
      class: 'Bottoms',
      department: 'Unisex Accessories',
      price: 114.99,
      cost: 60.94,
    },
    {
      id: 'SK01549',
      name: 'Faux Suede Ankle Boots',
      class: 'Tops',
      department: 'Sportswear',
      price: 94.99,
      cost: 71.53,
    },
    {
      id: 'SK01566',
      name: 'Striped Cotton Socks',
      class: 'Accessories',
      department: 'Sportswear',
      price: 9.99,
      cost: 6.91,
    },
    {
      id: 'SK01642',
      name: 'Performance Compression Tights',
      class: 'Outerwear',
      department: 'Sportswear',
      price: 54.99,
      cost: 59.61,
    },
    {
      id: 'SK01733',
      name: 'Vintage Logo Hoodie',
      class: 'Accessories',
      department: "Men's Apparel",
      price: 94.99,
      cost: 84.45,
    },
    {
      id: 'SK01896',
      name: 'Floral Chiffon Wrap Dress',
      class: 'Accessories',
      department: 'Unisex Accessories',
      price: 149.99,
      cost: 68.55,
    },
    {
      id: 'SK01927',
      name: 'Asymmetrical Hem Skirt',
      class: 'Jewelry',
      department: 'Sportswear',
      price: 99.99,
      cost: 66.89,
    },
    {
      id: 'SK01950',
      name: 'Slim Fit Pinstripe Suit',
      class: 'Bottoms',
      department: "Women's Apparel",
      price: 99.99,
      cost: 13.3,
    },
    {
      id: 'SK02029',
      name: 'Chunky Heel Sandals',
      class: 'Jewelry',
      department: 'Unisex Accessories',
      price: 89.99,
      cost: 46.7,
    },
    {
      id: 'SK02429',
      name: 'Suede Fringe Vest',
      class: 'Bottoms',
      department: 'Footwear',
      price: 184.99,
      cost: 159.65,
    },
    {
      id: 'SK02448',
      name: 'Relaxed Fit Cargo Pants',
      class: 'Bottoms',
      department: 'Sportswear',
      price: 149.99,
      cost: 7.2,
    },
    {
      id: 'SK02562',
      name: 'Corduroy A-Line Skirt',
      class: 'Jewelry',
      department: 'Footwear',
      price: 129.99,
      cost: 48.62,
    },
    {
      id: 'SK02642',
      name: 'Formal Dress Shoes',
      class: 'Bottoms',
      department: "Women's Apparel",
      price: 164.99,
      cost: 161.69,
    },
    {
      id: 'SK02768',
      name: 'Tailored Corduroy Blazer',
      class: 'Accessories',
      department: 'Sportswear',
      price: 89.99,
      cost: 62.99,
    },
    {
      id: 'SK02805',
      name: 'Foldable Travel Hat',
      class: 'Outerwear',
      department: "Women's Apparel",
      price: 194.99,
      cost: 56.16,
    },
    {
      id: 'SK02904',
      name: 'Asymmetrical Hem Skirt',
      class: 'Tops',
      department: 'Unisex Accessories',
      price: 89.99,
      cost: 67.94,
    },
    {
      id: 'SK03182',
      name: 'Plaid Flannel Shirt',
      class: 'Tops',
      department: 'Unisex Accessories',
      price: 124.99,
      cost: 17.5,
    },
    {
      id: 'SK03289',
      name: 'Oversized Hoodie',
      class: 'Tops',
      department: "Women's Apparel",
      price: 159.99,
      cost: 122.23,
    },
    {
      id: 'SK03348',
      name: 'Woven Straw Sun Hat',
      class: 'Jewelry',
      department: 'Footwear',
      price: 164.99,
      cost: 8.91,
    },
    {
      id: 'SK03569',
      name: 'Faux Fur Winter Coat',
      class: 'Tops',
      department: "Men's Apparel",
      price: 9.99,
      cost: 7.37,
    },
    {
      id: 'SK03572',
      name: 'Casual Cotton Romper',
      class: 'Tops',
      department: 'Footwear',
      price: 119.99,
      cost: 52.32,
    },
    {
      id: 'SK03636',
      name: 'Racerback Sports Bra',
      class: 'Footwear',
      department: 'Unisex Accessories',
      price: 14.99,
      cost: 8.72,
    },
    {
      id: 'SK03725',
      name: 'Polarized Sports Sunglasses',
      class: 'Tops',
      department: "Men's Apparel",
      price: 79.99,
      cost: 9.44,
    },
    {
      id: 'SK03980',
      name: 'Chunky Platform Sneakers',
      class: 'Tops',
      department: 'Unisex Accessories',
      price: 109.99,
      cost: 61.7,
    },
    {
      id: 'SK04282',
      name: 'Slim Fit Chinos',
      class: 'Footwear',
      department: 'Sportswear',
      price: 114.99,
      cost: 51.98,
    },
    {
      id: 'SK04325',
      name: 'Faux Leather Leggings',
      class: 'Tops',
      department: 'Footwear',
      price: 194.99,
      cost: 13.06,
    },
    {
      id: 'SK04707',
      name: 'Water-Resistant Fanny Pack',
      class: 'Tops',
      department: "Women's Apparel",
      price: 24.99,
      cost: 23.64,
    },
    {
      id: 'SK04815',
      name: 'Performance Compression Tights',
      class: 'Bottoms',
      department: 'Footwear',
      price: 14.99,
      cost: 16.29,
    },
    {
      id: 'SK05097',
      name: 'Cropped Faux Leather Jacket',
      class: 'Jewelry',
      department: 'Sportswear',
      price: 79.99,
      cost: 19.52,
    },
    {
      id: 'SK05194',
      name: 'Breathable Mesh Shorts',
      class: 'Accessories',
      department: 'Footwear',
      price: 194.99,
      cost: 28.08,
    },
    {
      id: 'SK05478',
      name: 'Minimalist Silver Ring',
      class: 'Accessories',
      department: 'Footwear',
      price: 174.99,
      cost: 147.34,
    },
    {
      id: 'SK05715',
      name: 'Ribbed Turtleneck Dress',
      class: 'Bottoms',
      department: 'Footwear',
      price: 94.99,
      cost: 22.61,
    },
    {
      id: 'SK05928',
      name: 'Velvet Slip Dress',
      class: 'Jewelry',
      department: "Men's Apparel",
      price: 69.99,
      cost: 41.64,
    },
    {
      id: 'SK06290',
      name: 'Waterproof Smartwatch',
      class: 'Bottoms',
      department: "Men's Apparel",
      price: 144.99,
      cost: 53.5,
    },
    {
      id: 'SK06375',
      name: 'Patterned Cotton Bucket Hat',
      class: 'Outerwear',
      department: 'Sportswear',
      price: 144.99,
      cost: 114.4,
    },
    {
      id: 'SK06559',
      name: 'Diamond Stud Earrings',
      class: 'Outerwear',
      department: "Men's Apparel",
      price: 144.99,
      cost: 146.0,
    },
    {
      id: 'SK06601',
      name: 'Tassel Fringe Handbag',
      class: 'Outerwear',
      department: 'Unisex Accessories',
      price: 59.99,
      cost: 33.29,
    },
    {
      id: 'SK06651',
      name: 'Tactical Hiking Backpack',
      class: 'Outerwear',
      department: 'Sportswear',
      price: 49.99,
      cost: 52.54,
    },
    {
      id: 'SK06691',
      name: 'Patterned Cotton Bucket Hat',
      class: 'Accessories',
      department: 'Unisex Accessories',
      price: 9.99,
      cost: 2.14,
    },
    {
      id: 'SK06996',
      name: 'Bohemian Beaded Bracelet',
      class: 'Accessories',
      department: 'Unisex Accessories',
      price: 124.99,
      cost: 116.12,
    },
    {
      id: 'SK07054',
      name: 'Mesh Panel Yoga Pants',
      class: 'Accessories',
      department: 'Footwear',
      price: 184.99,
      cost: 166.86,
    },
    {
      id: 'SK07068',
      name: 'Diamond Stud Earrings',
      class: 'Outerwear',
      department: 'Sportswear',
      price: 14.99,
      cost: 13.75,
    },
    {
      id: 'SK07322',
      name: 'Faux Suede Ankle Boots',
      class: 'Tops',
      department: 'Footwear',
      price: 84.99,
      cost: 90.43,
    },
    {
      id: 'SK07369',
      name: 'Water-Resistant Fanny Pack',
      class: 'Outerwear',
      department: 'Unisex Accessories',
      price: 4.99,
      cost: 3.73,
    },
    {
      id: 'SK07447',
      name: 'Plaid Wool Scarf',
      class: 'Tops',
      department: 'Footwear',
      price: 139.99,
      cost: 97.57,
    },
    {
      id: 'SK07484',
      name: 'Cropped Faux Leather Jacket',
      class: 'Accessories',
      department: "Women's Apparel",
      price: 179.99,
      cost: 163.43,
    },
    {
      id: 'SK07595',
      name: 'Textured Knit Pullover',
      class: 'Tops',
      department: 'Footwear',
      price: 54.99,
      cost: 50.43,
    },
    {
      id: 'SK07767',
      name: 'Boho Style Tassel Earrings',
      class: 'Footwear',
      department: 'Sportswear',
      price: 194.99,
      cost: 193.43,
    },
    {
      id: 'SK07782',
      name: 'Sherpa Lined Hooded Coat',
      class: 'Jewelry',
      department: 'Footwear',
      price: 174.99,
      cost: 128.09,
    },
    {
      id: 'SK07944',
      name: 'Mesh Panel Yoga Pants',
      class: 'Tops',
      department: 'Unisex Accessories',
      price: 69.99,
      cost: 45.49,
    },
    {
      id: 'SK08191',
      name: 'Graphic Print T-Shirt',
      class: 'Jewelry',
      department: "Men's Apparel",
      price: 109.99,
      cost: 53.35,
    },
    {
      id: 'SK08285',
      name: 'Fitted V-Neck Sweater',
      class: 'Footwear',
      department: "Men's Apparel",
      price: 124.99,
      cost: 110.24,
    },
    {
      id: 'SK08314',
      name: 'Formal Dress Shoes',
      class: 'Accessories',
      department: 'Footwear',
      price: 74.99,
      cost: 8.62,
    },
    {
      id: 'SK08373',
      name: 'Satin Lace Camisole',
      class: 'Jewelry',
      department: "Women's Apparel",
      price: 184.99,
      cost: 136.15,
    },
    {
      id: 'SK08443',
      name: 'Slim Fit Chinos',
      class: 'Bottoms',
      department: 'Unisex Accessories',
      price: 89.99,
      cost: 61.64,
    },
    {
      id: 'SK08544',
      name: 'Retro-Inspired Sunglasses',
      class: 'Footwear',
      department: "Women's Apparel",
      price: 44.99,
      cost: 41.12,
    },
    {
      id: 'SK08557',
      name: 'Formal Velvet Blazer',
      class: 'Bottoms',
      department: 'Sportswear',
      price: 194.99,
      cost: 189.14,
    },
    {
      id: 'SK08783',
      name: 'Striped Cotton Socks',
      class: 'Accessories',
      department: 'Footwear',
      price: 169.99,
      cost: 10.54,
    },
    {
      id: 'SK09245',
      name: 'Yoga Leggings',
      class: 'Bottoms',
      department: 'Unisex Accessories',
      price: 164.99,
      cost: 172.58,
    },
    {
      id: 'SK09312',
      name: 'Formal Dress Shoes',
      class: 'Bottoms',
      department: 'Sportswear',
      price: 9.99,
      cost: 1.96,
    },
    {
      id: 'SK09318',
      name: 'Aviator Sunglasses',
      class: 'Footwear',
      department: 'Sportswear',
      price: 44.99,
      cost: 12.37,
    },
    {
      id: 'SK09414',
      name: 'Perforated Leather Belt',
      class: 'Tops',
      department: 'Footwear',
      price: 44.99,
      cost: 4.5,
    },
    {
      id: 'SK09453',
      name: 'Smart Heated Gloves',
      class: 'Footwear',
      department: 'Unisex Accessories',
      price: 109.99,
      cost: 100.53,
    },
    {
      id: 'SK09469',
      name: 'Silk Embroidered Kimono',
      class: 'Jewelry',
      department: 'Sportswear',
      price: 109.99,
      cost: 78.64,
    },
    {
      id: 'SK09592',
      name: 'Performance Swim Trunks',
      class: 'Tops',
      department: "Men's Apparel",
      price: 174.99,
      cost: 157.84,
    },
    {
      id: 'SK09659',
      name: 'Tactical Hiking Backpack',
      class: 'Jewelry',
      department: "Women's Apparel",
      price: 69.99,
      cost: 58.16,
    },
    {
      id: 'SK09728',
      name: 'Thermal Running Gloves',
      class: 'Outerwear',
      department: "Women's Apparel",
      price: 49.99,
      cost: 53.79,
    },
    {
      id: 'SK09816',
      name: 'Quilted Leather Clutch',
      class: 'Jewelry',
      department: 'Unisex Accessories',
      price: 134.99,
      cost: 95.84,
    },
    {
      id: 'SK10226',
      name: 'Rugged Utility Jacket',
      class: 'Accessories',
      department: 'Unisex Accessories',
      price: 44.99,
      cost: 2.43,
    },
    {
      id: 'SK10286',
      name: 'Tapered Suit Trousers',
      class: 'Bottoms',
      department: "Men's Apparel",
      price: 64.99,
      cost: 53.1,
    },
    {
      id: 'SK10304',
      name: 'Faux Leather Leggings',
      class: 'Tops',
      department: "Men's Apparel",
      price: 139.99,
      cost: 22.54,
    },
    {
      id: 'SK10514',
      name: 'Lace-Up Combat Boots',
      class: 'Tops',
      department: 'Sportswear',
      price: 109.99,
      cost: 64.89,
    },
    {
      id: 'SK10565',
      name: 'Athletic Crew Socks',
      class: 'Accessories',
      department: 'Unisex Accessories',
      price: 174.99,
      cost: 1.75,
    },
    {
      id: 'SK10717',
      name: 'Silk Neck Scarf',
      class: 'Outerwear',
      department: 'Footwear',
      price: 94.99,
      cost: 49.87,
    },
    {
      id: 'SK10760',
      name: 'Sherpa Lined Denim Jacket',
      class: 'Outerwear',
      department: "Women's Apparel",
      price: 119.99,
      cost: 28.92,
    },
  ];

  // Create months
  const months: Month[] = [
    { id: 'month-1', name: 'February 2024' },
    { id: 'month-2', name: 'March 2024' },
    { id: 'month-3', name: 'April 2024' },
    { id: 'month-4', name: 'May 2024' },
    { id: 'month-5', name: 'June 2024' },
    { id: 'month-6', name: 'July 2024' },
    { id: 'month-7', name: 'August 2024' },
    { id: 'month-8', name: 'September 2024' },
    { id: 'month-9', name: 'October 2024' },
    { id: 'month-10', name: 'November 2024' },
    { id: 'month-11', name: 'December 2024' },
    { id: 'month-12', name: 'January 2025' },
    { id: 'month-13', name: 'February 2025' },
  ];

  // Create weeks (4-5 weeks per month)
  const weeks: Week[] = [
    // February 2024
    { id: 'week-1', name: 'Week 1', monthId: 'month-1' },
    { id: 'week-2', name: 'Week 2', monthId: 'month-1' },
    { id: 'week-3', name: 'Week 3', monthId: 'month-1' },
    { id: 'week-4', name: 'Week 4', monthId: 'month-1' },

    // March 2024
    { id: 'week-5', name: 'Week 5', monthId: 'month-2' },
    { id: 'week-6', name: 'Week 6', monthId: 'month-2' },
    { id: 'week-7', name: 'Week 7', monthId: 'month-2' },
    { id: 'week-8', name: 'Week 8', monthId: 'month-2' },
    { id: 'week-9', name: 'Week 9', monthId: 'month-2' },

    // April 2024
    { id: 'week-10', name: 'Week 10', monthId: 'month-3' },
    { id: 'week-11', name: 'Week 11', monthId: 'month-3' },
    { id: 'week-12', name: 'Week 12', monthId: 'month-3' },
    { id: 'week-13', name: 'Week 13', monthId: 'month-3' },

    // May 2024
    { id: 'week-14', name: 'Week 14', monthId: 'month-4' },
    { id: 'week-15', name: 'Week 15', monthId: 'month-4' },
    { id: 'week-16', name: 'Week 16', monthId: 'month-4' },
    { id: 'week-17', name: 'Week 17', monthId: 'month-4' },

    // June 2024
    { id: 'week-18', name: 'Week 18', monthId: 'month-5' },
    { id: 'week-19', name: 'Week 19', monthId: 'month-5' },
    { id: 'week-20', name: 'Week 20', monthId: 'month-5' },
    { id: 'week-21', name: 'Week 21', monthId: 'month-5' },
    { id: 'week-22', name: 'Week 22', monthId: 'month-5' },

    // July 2024
    { id: 'week-23', name: 'Week 23', monthId: 'month-6' },
    { id: 'week-24', name: 'Week 24', monthId: 'month-6' },
    { id: 'week-25', name: 'Week 25', monthId: 'month-6' },
    { id: 'week-26', name: 'Week 26', monthId: 'month-6' },

    // August 2024
    { id: 'week-27', name: 'Week 27', monthId: 'month-7' },
    { id: 'week-28', name: 'Week 28', monthId: 'month-7' },
    { id: 'week-29', name: 'Week 29', monthId: 'month-7' },
    { id: 'week-30', name: 'Week 30', monthId: 'month-7' },
    { id: 'week-31', name: 'Week 31', monthId: 'month-7' },

    // September 2024
    { id: 'week-32', name: 'Week 32', monthId: 'month-8' },
    { id: 'week-33', name: 'Week 33', monthId: 'month-8' },
    { id: 'week-34', name: 'Week 34', monthId: 'month-8' },
    { id: 'week-35', name: 'Week 35', monthId: 'month-8' },

    // October 2024
    { id: 'week-36', name: 'Week 36', monthId: 'month-9' },
    { id: 'week-37', name: 'Week 37', monthId: 'month-9' },
    { id: 'week-38', name: 'Week 38', monthId: 'month-9' },
    { id: 'week-39', name: 'Week 39', monthId: 'month-9' },
    { id: 'week-40', name: 'Week 40', monthId: 'month-9' },

    // November 2024
    { id: 'week-41', name: 'Week 41', monthId: 'month-10' },
    { id: 'week-42', name: 'Week 42', monthId: 'month-10' },
    { id: 'week-43', name: 'Week 43', monthId: 'month-10' },
    { id: 'week-44', name: 'Week 44', monthId: 'month-10' },

    // December 2024
    { id: 'week-45', name: 'Week 45', monthId: 'month-11' },
    { id: 'week-46', name: 'Week 46', monthId: 'month-11' },
    { id: 'week-47', name: 'Week 47', monthId: 'month-11' },
    { id: 'week-48', name: 'Week 48', monthId: 'month-11' },
    { id: 'week-49', name: 'Week 49', monthId: 'month-11' },

    // January 2025
    { id: 'week-50', name: 'Week 50', monthId: 'month-12' },
    { id: 'week-51', name: 'Week 51', monthId: 'month-12' },
    { id: 'week-52', name: 'Week 52', monthId: 'month-12' },
    { id: 'week-53', name: 'Week 53', monthId: 'month-12' },

    // February 2025
    { id: 'week-54', name: 'Week 54', monthId: 'month-13' },
    { id: 'week-55', name: 'Week 55', monthId: 'month-13' },
    { id: 'week-56', name: 'Week 56', monthId: 'month-13' },
    { id: 'week-57', name: 'Week 57', monthId: 'month-13' },
  ];

  // Create random planning data
  const planningData: PlanningData[] = [];

  stores.forEach((store) => {
    skus.forEach((sku) => {
      weeks.forEach((week) => {
        // Generate random sales units between 5 and 100
        const salesUnits = Math.floor(Math.random() * 95) + 5;

        planningData.push({
          storeId: store.id,
          skuId: sku.id,
          weekId: week.id,
          salesUnits,
        });
      });
    });
  });

  return {
    stores,
    skus,
    weeks,
    months,
    planningData,
  };
};
